### ISSUE TITLE
(Backend) - Create a function that will calculate coordinate pairs given 4 coordinate pairs as input

### ISSUE THREAD

**Issue by edman90** [edman90/3DTable#6]
The front end will send four pairs of coordinates that will represent the edges of the rectangular area the selected edges. The backend should sample 14 coordinates that are close to being equidistant throughout the selected area.

**Comment by edman90** [comment]
Create a function that receives 4 pairs of coordinates as input, each coordinate pair representing a corner of the user's rectangular selection, and then calculate N coordinate pairs within the 4 coordinates to build a coordinate dataset. This coordinate dataset will represent the area are mapping. So given 4 coordinate pairs as input, let's start with calculating 16 evenly spaced coordinate pairs for now.

**Comment by will-pavlick** [comment]
Done
